/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
*/
/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
  var sHash ={}, tHash ={};
  for (let i = 0; i < s.length; i++) {
    if (!sHash[s[i]]) {
      sHash[s[i]] = 1;
    } else {
      sHash[s[i]]++;
    }
    
  }
  for (let j = 0; j < t.length; j++) {
    if (!tHash[t[j]]) {
      tHash[t[j]] = 1;
    } else {
      tHash[t[j]]++;
    }
  }

  var tHashKeys = Object.keys(tHash);
  for (let i = 0; i < tHashKeys.length; i++) {
    if (tHash[tHashKeys[i]] !== sHash[tHashKeys[i]]) {
      return tHashKeys[i];
    }
  }
  
};

// findTheDifference("sdfds", "sdfdss");
findTheDifference("sdfds", "sdfdst");